### ISSUE TITLE
你好，我想问下怎么运行你的项目

### ISSUE THREAD

**Issue by lyimin** [avplayer/AVCamera#2]
你好，我想问下怎么运行你的项目

**Comment by lyimin** [comment]
xcode可以运行吗？

**Comment by whyb** [comment]
@lyimin ,xcode是可以運行的，本項目中有QT版本的也有MFC版本的。

**Comment by lyimin** [comment]
xcode貌似不能打开哦，mfc里面有个文件后缀是vcxproj，而xcode的项目一般后缀是xcodeproj

**Comment by whyb** [comment]
@lyimin 請用CMake釋出xcodeproj

**Comment by lyimin** [comment]
好，谢谢，我研究一下
